# Classifying Penguins with Keras

In [29]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn import preprocessing
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, roc_curve

In [30]:
! pip install palmerpenguins
from palmerpenguins import load_penguins
penguins = load_penguins()
penguins = penguins.dropna()
penguins.head()

Requirement already satisfied: palmerpenguins in ./.conda-env/lib/python3.12/site-packages (0.1.6)
Requirement already satisfied: pandas in ./.conda-env/lib/python3.12/site-packages (from palmerpenguins) (3.0.3)
Requirement already satisfied: numpy in ./.conda-env/lib/python3.12/site-packages (from palmerpenguins) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.conda-env/lib/python3.12/site-packages (from pandas->palmerpenguins) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.conda-env/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->palmerpenguins) (1.17.0)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,2007

In [31]:
#SHUFFLE THE DATA
penguins = penguins.sample(frac=1).reset_index(drop=True)
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Gentoo,Biscoe,50.1,15.0,225.0,5000.0,male,2008
1,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,male,2009
2,Adelie,Dream,43.2,18.5,192.0,4100.0,male,2008
3,Adelie,Biscoe,41.6,18.0,192.0,3950.0,male,2008
4,Adelie,Biscoe,37.6,19.1,194.0,3750.0,male,2008

In [32]:
penguins_x = pd.concat([penguins[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm']], pd.get_dummies(penguins['sex'])], axis = 1)
# penguins_x = penguins_x[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'female', 'male']]
penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,5000.0,50.1,15.0,225.0,False,True
1,5400.0,49.9,16.1,213.0,False,True
2,4100.0,43.2,18.5,192.0,False,True
3,3950.0,41.6,18.0,192.0,False,True
4,3750.0,37.6,19.1,194.0,False,True
...,...,...,...,...,...,...
328,4000.0,42.1,19.1,195.0,False,True
329,4150.0,52.0,19.0,197.0,False,True
330,4400.0,45.1,14.4,210.0,True,False
331,4775.0,43.2,19.0,197.0,False,True
332,5400.0,48.4,16.3,220.0,False,True

In [33]:
x = penguins_x.values
min_max_scaler = preprocessing.MinMaxScaler()
scaled_penguins_x = pd.DataFrame(min_max_scaler.fit_transform(x), columns=penguins_x.columns)
scaled_penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,0.638889,0.654545,0.226190,0.898305,0.0,1.0
1,0.750000,0.647273,0.357143,0.694915,0.0,1.0
2,0.388889,0.403636,0.642857,0.338983,0.0,1.0
3,0.347222,0.345455,0.583333,0.338983,0.0,1.0
4,0.291667,0.200000,0.714286,0.372881,0.0,1.0
...,...,...,...,...,...,...
328,0.361111,0.363636,0.714286,0.389831,0.0,1.0
329,0.402778,0.723636,0.702381,0.423729,0.0,1.0
330,0.472222,0.472727,0.154762,0.644068,1.0,0.0
331,0.576389,0.403636,0.702381,0.423729,0.0,1.0
332,0.750000,0.592727,0.380952,0.813559,0.0,1.0

In [34]:
penguins_y = penguins['species']
print(penguins_y)
penguins_y = penguins_y.astype('category').cat.codes.to_numpy()
penguins_y

0         Gentoo
1         Gentoo
2         Adelie
3         Adelie
4         Adelie
         ...
328       Adelie
329    Chinstrap
330       Gentoo
331       Adelie
332       Gentoo
Name: species, Length: 333, dtype: str

array([2, 2, 0, 0, 0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 1, 0, 2, 0, 2, 0, 2, 0,
       1, 2, 0, 1, 0, 1, 1, 0, 0, 1, 0, 2, 2, 0, 2, 0, 2, 2, 1, 2, 1, 0,
       1, 0, 0, 0, 2, 2, 1, 2, 2, 0, 1, 1, 1, 0, 0, 2, 0, 0, 2, 0, 0, 2,
       2, 2, 0, 0, 0, 2, 2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 0, 0, 2, 0, 1, 1,
       0, 1, 2, 0, 1, 0, 0, 1, 0, 0, 2, 0, 2, 0, 1, 2, 1, 2, 0, 0, 0, 2,
       2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 0, 0, 2, 2, 2, 0, 2, 1, 2, 0, 2, 0,
       0, 2, 2, 1, 1, 2, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 2, 0, 2, 1, 2,
       0, 2, 2, 2, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 0, 1, 1,
       2, 2, 0, 1, 0, 0, 0, 0, 2, 2, 0, 2, 2, 2, 0, 2, 2, 1, 0, 2, 2, 0,
       1, 0, 0, 2, 1, 0, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 2, 0, 2, 1, 1, 1,
       0, 2, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 2, 0,
       2, 0, 0, 2, 1, 0, 0, 0, 2, 1, 0, 1, 1, 2, 2, 2, 0, 2, 2, 1, 1, 1,
       2, 1, 0, 2, 2, 1, 1, 2, 0, 0, 2, 1, 1, 2, 0, 1, 0, 2, 0, 2, 1, 0,
       0, 0, 2, 2, 2, 1, 0, 2, 2, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0,
       2, 2, 2, 0, 2, 2, 0, 1, 1, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 1,
       2, 0, 2], dtype=int8)

In [35]:
#construct the model
inputs = keras.Input(shape=(6,))
x = layers.Dense(7, activation = 'relu')(inputs)
x = layers.Dense(5, activation = 'relu')(x)
x = layers.Dense(3, activation = 'relu')(x)
outputs = layers.Dense(3, activation='softmax')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model")

In [36]:
model.summary()

Model: "penguin_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_2 (InputLayer)      │ (None, 6)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 7)              │            49 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 5)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 3)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 3)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 119 (476.00 B)

 Trainable params: 119 (476.00 B)

 Non-trainable params: 0 (0.00 B)

In [37]:
keras.utils.plot_model(model, show_shapes = True)

You must install pydot (`pip install pydot`) for `plot_model` to work.

In [38]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history = model.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs=100, validation_split=0.1)

scores = model.evaluate(scaled_penguins_x, penguins_y, verbose=2)

Epoch 1/100

/Users/mkenne16/Documents/Advanced Machine Learning/week 7/.conda-env/lib/python3.12/site-packages/keras/src/backend/tensorflow/nn.py:1216: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 128ms/step - accuracy: 0.4047 - loss: 1.0973 - val_accuracy: 0.4118 - val_loss: 1.0946
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0955 - val_accuracy: 0.4118 - val_loss: 1.0928
Epoch 3/100
1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.3750 - loss: 1.0948

/Users/mkenne16/Documents/Advanced Machine Learning/week 7/.conda-env/lib/python3.12/site-packages/keras/src/backend/tensorflow/nn.py:1216: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0944 - val_accuracy: 0.4118 - val_loss: 1.0912
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.4415 - loss: 1.0934 - val_accuracy: 0.4118 - val_loss: 1.0898
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.4415 - loss: 1.0924 - val_accuracy: 0.4118 - val_loss: 1.0885
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0915 - val_accuracy: 0.4118 - val_loss: 1.0874
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0907 - val_accuracy: 0.4118 - val_loss: 1.0862
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0898 - val_accuracy: 0.4118 - val_loss: 1.0850
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0890 - val_accuracy: 0.4118 - val_loss: 1.0838
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0882 - val_accuracy: 0.4118 - val_loss: 1.0827
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0873 - val_accuracy: 0.4118 - val_loss: 1.0815
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0865 - val_accuracy: 0.4118 - val_loss: 1.0803
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0857 - val_accuracy: 0.4118 - val_loss: 1.0791
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0849 - val_accuracy: 0.4118 - val_loss: 1.0777
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0842 - val_accuracy: 0.4118 - val_loss: 1.0764
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0833 - val_accuracy: 0.4118 - val_loss: 1.0754
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0826 - val_accuracy: 0.4118 - val_loss: 1.0742
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0819 - val_accuracy: 0.4118 - val_loss: 1.0730
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0812 - val_accuracy: 0.4118 - val_loss: 1.0718
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0805 - val_accuracy: 0.4118 - val_loss: 1.0709
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.4415 - loss: 1.0798 - val_accuracy: 0.4118 - val_loss: 1.0697
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4415 - loss: 1.0791 - val_accuracy: 0.4118 - val_loss: 1.0686
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0784 - val_accuracy: 0.4118 - val_loss: 1.0675
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0778 - val_accuracy: 0.4118 - val_loss: 1.0665
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0771 - val_accuracy: 0.4118 - val_loss: 1.0656
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0766 - val_accuracy: 0.4118 - val_loss: 1.0647
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0761 - val_accuracy: 0.4118 - val_loss: 1.0638
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0755 - val_accuracy: 0.4118 - val_loss: 1.0628
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0749 - val_accuracy: 0.4118 - val_loss: 1.0620
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0743 - val_accuracy: 0.4118 - val_loss: 1.0612
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0738 - val_accuracy: 0.4118 - val_loss: 1.0603
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0733 - val_accuracy: 0.4118 - val_loss: 1.0594
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0728 - val_accuracy: 0.4118 - val_loss: 1.0585
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0723 - val_accuracy: 0.4118 - val_loss: 1.0576
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0717 - val_accuracy: 0.4118 - val_loss: 1.0567
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0712 - val_accuracy: 0.4118 - val_loss: 1.0560
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0709 - val_accuracy: 0.4118 - val_loss: 1.0553
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0705 - val_accuracy: 0.4118 - val_loss: 1.0546
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0700 - val_accuracy: 0.4118 - val_loss: 1.0538
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0696 - val_accuracy: 0.4118 - val_loss: 1.0529
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0692 - val_accuracy: 0.4118 - val_loss: 1.0521
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0688 - val_accuracy: 0.4118 - val_loss: 1.0513
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4415 - loss: 1.0683 - val_accuracy: 0.4118 - val_loss: 1.0507
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4415 - loss: 1.0679 - val_accuracy: 0.4118 - val_loss: 1.0500
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.4415 - loss: 1.0675 - val_accuracy: 0.4118 - val_loss: 1.0492
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.4415 - loss: 1.0671 - val_accuracy: 0.4118 - val_loss: 1.0486
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.4415 - loss: 1.0668 - val_accuracy: 0.4118 - val_loss: 1.0480
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.4415 - loss: 1.0665 - val_accuracy: 0.4118 - val_loss: 1.0473
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.4415 - loss: 1.0661 - val_accuracy: 0.4118 - val_loss: 1.0467
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4415 - loss: 1.0658 - val_accuracy: 0.4118 - val_loss: 1.0461
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4415 - loss: 1.0655 - val_accuracy: 0.4118 - val_loss: 1.0456
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4415 - loss: 1.0652 - val_accuracy: 0.4118 - val_loss: 1.0451
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0650 - val_accuracy: 0.4118 - val_loss: 1.0444
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0646 - val_accuracy: 0.4118 - val_loss: 1.0439
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.4415 - loss: 1.0644 - val_accuracy: 0.4118 - val_loss: 1.0433
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4415 - loss: 1.0642 - val_accuracy: 0.4118 - val_loss: 1.0426
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0639 - val_accuracy: 0.4118 - val_loss: 1.0420
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4415 - loss: 1.0637 - val_accuracy: 0.4118 - val_loss: 1.0415
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4415 - loss: 1.0634 - val_accuracy: 0.4118 - val_loss: 1.0410
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4415 - loss: 1.0632 - val_accuracy: 0.4118 - val_loss: 1.0406
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0630 - val_accuracy: 0.4118 - val_loss: 1.0401
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0628 - val_accuracy: 0.4118 - val_loss: 1.0397
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0626 - val_accuracy: 0.4118 - val_loss: 1.0394
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0624 - val_accuracy: 0.4118 - val_loss: 1.0388
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0623 - val_accuracy: 0.4118 - val_loss: 1.0385
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0621 - val_accuracy: 0.4118 - val_loss: 1.0382
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0620 - val_accuracy: 0.4118 - val_loss: 1.0378
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4415 - loss: 1.0617 - val_accuracy: 0.4118 - val_loss: 1.0374
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.4415 - loss: 1.0616 - val_accuracy: 0.4118 - val_loss: 1.0370
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0615 - val_accuracy: 0.4118 - val_loss: 1.0367
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0613 - val_accuracy: 0.4118 - val_loss: 1.0362
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0612 - val_accuracy: 0.4118 - val_loss: 1.0359
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0610 - val_accuracy: 0.4118 - val_loss: 1.0357
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 128ms/step - accuracy: 0.4415 - loss: 1.0610 - val_accuracy: 0.4118 - val_loss: 1.0353
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.4415 - loss: 1.0608 - val_accuracy: 0.4118 - val_loss: 1.0350
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.4415 - loss: 1.0607 - val_accuracy: 0.4118 - val_loss: 1.0347
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.4415 - loss: 1.0605 - val_accuracy: 0.4118 - val_loss: 1.0345
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.4415 - loss: 1.0604 - val_accuracy: 0.4118 - val_loss: 1.0340
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.4415 - loss: 1.0604 - val_accuracy: 0.4118 - val_loss: 1.0336
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.4415 - loss: 1.0602 - val_accuracy: 0.4118 - val_loss: 1.0334
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.4415 - loss: 1.0602 - val_accuracy: 0.4118 - val_loss: 1.0332
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4415 - loss: 1.0601 - val_accuracy: 0.4118 - val_loss: 1.0329
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.4415 - loss: 1.0600 - val_accuracy: 0.4118 - val_loss: 1.0325
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4415 - loss: 1.0600 - val_accuracy: 0.4118 - val_loss: 1.0324
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.4415 - loss: 1.0598 - val_accuracy: 0.4118 - val_loss: 1.0322
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.4415 - loss: 1.0598 - val_accuracy: 0.4118 - val_loss: 1.0319
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.4415 - loss: 1.0596 - val_accuracy: 0.4118 - val_loss: 1.0315
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.4415 - loss: 1.0596 - val_accuracy: 0.4118 - val_loss: 1.0311
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4415 - loss: 1.0595 - val_accuracy: 0.4118 - val_loss: 1.0308
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0595 - val_accuracy: 0.4118 - val_loss: 1.0305
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0594 - val_accuracy: 0.4118 - val_loss: 1.0303
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.4415 - loss: 1.0594 - val_accuracy: 0.4118 - val_loss: 1.0300
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0592 - val_accuracy: 0.4118 - val_loss: 1.0298
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0592 - val_accuracy: 0.4118 - val_loss: 1.0294
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4415 - loss: 1.0591 - val_accuracy: 0.4118 - val_loss: 1.0292
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0591 - val_accuracy: 0.4118 - val_loss: 1.0289
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0591 - val_accuracy: 0.4118 - val_loss: 1.0286
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0590 - val_accuracy: 0.4118 - val_loss: 1.0283
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0590 - val_accuracy: 0.4118 - val_loss: 1.0282
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0590 - val_accuracy: 0.4118 - val_loss: 1.0279
11/11 - 0s - 3ms/step - accuracy: 0.4384 - loss: 1.0557

In [39]:
model_logit_true = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model_scaled")

model_logit_true.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history_logit_true = model_logit_true.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs = 100, validation_split = 0.1)

scores = model_logit_true.evaluate(scaled_penguins_x, penguins_y, verbose = 2)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.4415 - loss: 1.0588 - val_accuracy: 0.4118 - val_loss: 1.0266
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0588 - val_accuracy: 0.4118 - val_loss: 1.0263
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0587 - val_accuracy: 0.4118 - val_loss: 1.0261
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0587 - val_accuracy: 0.4118 - val_loss: 1.0260
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.4415 - loss: 1.0586 - val_accuracy: 0.4118 - val_loss: 1.0258
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0586 - val_accuracy: 0.4118 - val_loss: 1.0256
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0586 - val_accuracy: 0.4118 - val_loss: 1.0254
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0585 - val_accuracy: 0.4118 - val_loss: 1.0253
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0585 - val_accuracy: 0.4118 - val_loss: 1.0252
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0585 - val_accuracy: 0.4118 - val_loss: 1.0251
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0585 - val_accuracy: 0.4118 - val_loss: 1.0249
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0585 - val_accuracy: 0.4118 - val_loss: 1.0249
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0585 - val_accuracy: 0.4118 - val_loss: 1.0248
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.4415 - loss: 1.0584 - val_accuracy: 0.4118 - val_loss: 1.0248
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.4415 - loss: 1.0584 - val_accuracy: 0.4118 - val_loss: 1.0246
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.4415 - loss: 1.0584 - val_accuracy: 0.4118 - val_loss: 1.0246
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.4415 - loss: 1.0584 - val_accuracy: 0.4118 - val_loss: 1.0245
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4415 - loss: 1.0584 - val_accuracy: 0.4118 - val_loss: 1.0243
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4415 - loss: 1.0583 - val_accuracy: 0.4118 - val_loss: 1.0241
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4415 - loss: 1.0583 - val_accuracy: 0.4118 - val_loss: 1.0239
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0583 - val_accuracy: 0.4118 - val_loss: 1.0237
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0584 - val_accuracy: 0.4118 - val_loss: 1.0235
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0583 - val_accuracy: 0.4118 - val_loss: 1.0233
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0231
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0583 - val_accuracy: 0.4118 - val_loss: 1.0229
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0583 - val_accuracy: 0.4118 - val_loss: 1.0228
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0583 - val_accuracy: 0.4118 - val_loss: 1.0228
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0228
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4415 - loss: 1.0583 - val_accuracy: 0.4118 - val_loss: 1.0227
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0583 - val_accuracy: 0.4118 - val_loss: 1.0227
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0225
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0583 - val_accuracy: 0.4118 - val_loss: 1.0225
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0583 - val_accuracy: 0.4118 - val_loss: 1.0225
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0583 - val_accuracy: 0.4118 - val_loss: 1.0225
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0225
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0225
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0225
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0223
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0223
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0223
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0222
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0583 - val_accuracy: 0.4118 - val_loss: 1.0221
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0221
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0220
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0583 - val_accuracy: 0.4118 - val_loss: 1.0219
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0218
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0218
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0217
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0217
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0215
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0216
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0216
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0214
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0213
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0213
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0213
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0212
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0213
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0211
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0210
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0210
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0209
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0209
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0208
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0207
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0207
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0206
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0206
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0206
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0205
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0205
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0204
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0204
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0203
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0204
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0204
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0203
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0204
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0204
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0203
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0204
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0204
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4415 - loss: 1.0583 - val_accuracy: 0.4118 - val_loss: 1.0204
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0204
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0204
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0204
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0204
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0205
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0204
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0205
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0205
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0205
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0204
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0203
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0204
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0582 - val_accuracy: 0.4118 - val_loss: 1.0204
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0203
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0203
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0202
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.4415 - loss: 1.0581 - val_accuracy: 0.4118 - val_loss: 1.0202
11/11 - 0s - 4ms/step - accuracy: 0.4384 - loss: 1.0542

In [40]:
model_logit_true.predict(scaled_penguins_x)

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

array([[0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.4406446 , 0.2153228 , 0.34403268],
       [0.44064456, 0.21532279, 0.34403265]], dtype=float32)

In [41]:
penguins['species']

0         Gentoo
1         Gentoo
2         Adelie
3         Adelie
4         Adelie
         ...
328       Adelie
329    Chinstrap
330       Gentoo
331       Adelie
332       Gentoo
Name: species, Length: 333, dtype: str

In [42]:
penguins_y

array([2, 2, 0, 0, 0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 1, 0, 2, 0, 2, 0, 2, 0,
       1, 2, 0, 1, 0, 1, 1, 0, 0, 1, 0, 2, 2, 0, 2, 0, 2, 2, 1, 2, 1, 0,
       1, 0, 0, 0, 2, 2, 1, 2, 2, 0, 1, 1, 1, 0, 0, 2, 0, 0, 2, 0, 0, 2,
       2, 2, 0, 0, 0, 2, 2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 0, 0, 2, 0, 1, 1,
       0, 1, 2, 0, 1, 0, 0, 1, 0, 0, 2, 0, 2, 0, 1, 2, 1, 2, 0, 0, 0, 2,
       2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 0, 0, 2, 2, 2, 0, 2, 1, 2, 0, 2, 0,
       0, 2, 2, 1, 1, 2, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 2, 0, 2, 1, 2,
       0, 2, 2, 2, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 0, 1, 1,
       2, 2, 0, 1, 0, 0, 0, 0, 2, 2, 0, 2, 2, 2, 0, 2, 2, 1, 0, 2, 2, 0,
       1, 0, 0, 2, 1, 0, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 2, 0, 2, 1, 1, 1,
       0, 2, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 2, 0,
       2, 0, 0, 2, 1, 0, 0, 0, 2, 1, 0, 1, 1, 2, 2, 2, 0, 2, 2, 1, 1, 1,
       2, 1, 0, 2, 2, 1, 1, 2, 0, 0, 2, 1, 1, 2, 0, 1, 0, 2, 0, 2, 1, 0,
       0, 0, 2, 2, 2, 1, 0, 2, 2, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0,
       2, 2, 2, 0, 2, 2, 0, 1, 1, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 1,
       2, 0, 2], dtype=int8)